name: Test & Deploy Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    #   - name: Get Code
    #     uses: actions/checkout@v3
    #   - name: Run lint
    #     run: npm lint
      - name: Lint
        run: echo "Linting..."
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Run tests
        run: npm test
  buildndeploy:
    needs: [lint, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Run build
        run: npm run build
      - name: Deploy
        run: echo "Deploying...."
      
